### ISSUE TITLE
Config error during the install

### ISSUE THREAD

**Issue by PierreCapo** [xbase-lab/xbase#112]
When installing xbase, I receive a config error:

![image](https://user-images.githubusercontent.com/26744253/177360538-d58c10f1-2fb1-4855-8fc7-8685225cca4c.png)

Looks like the problem is located at [this line ](https://github.com/xbase-lab/xbase/blob/526e17ceaa5bdaf70df634a04eff08849a09d29c/lua/xbase/config.lua#L145) because `config.values.log_level` is nil

**Comment by kkharji** [comment]
@PierreCapo how about now can you check ?

**Comment by PierreCapo** [comment]
It looks like it is still broken ?
The stacktrace looks weird though, there is no mention of the `set_log_level` function that you have added, so I do wonder if it an issue that somehow Packer is not correctly using the correct version although I have specified the commit to pick

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/26744253/177509406-b8cbb352-d479-4e17-a9cb-e8ac6b47c6e4.png">

**Comment by kkharji** [comment]
> It looks like it is still broken ? The stacktrace looks weird though, there is no mention of the `set_log_level` function that you have added, so I do wonder if it an issue that somehow Packer is not correctly using the correct version although I have specified the commit to pick

Indeed that's odd, I'm looking  at the fix right now and I really don't like what I did, all this just to have the user set string representation of the level. That's it I'm going to change the log_level type to number, and users should just set it with `vim.log.levels.DEBUG` for example.

**Comment by PierreCapo** [comment]
This makes sense, less surface area for the xbase project to maintain for now 👍

**Comment by PierreCapo** [comment]
I have just tried, issue is indeed fixed in dc78bac85ba1eaa40d09b13a9beb436572d63eb7, thanks @kkharji 🙌
