### ISSUE TITLE
Can't get it to launch

### ISSUE THREAD

**Issue by andrestone** [xbase-lab/xbase#146]
Hey! Thanks for working on this, I couldn't believe when I saw it.

I've done everything as in the README, but still nothing happens and the log files aren't even generated.

I'm running on latest everything (nightly neovim), and sourcekit lsp works normally.

Is there anything I could do to troubleshoot?

Also, how am I suppose to use the feline provider? I tried to add it as a provider to a component but it didn't work.

**Comment by kkharji** [comment]
Hey @andrestone, 

First can you check if the make command resulted in two valid binaries located in `~/.local/share/xbase/`

Next, are you using a generator? what is the basic structure of your project. There is small chance your project wasn't detected.

One thing to try is to navigate to repo root and run `make install_debug`

**Comment by andrestone** [comment]
Hey @kkharji! Thanks for the prompt reply and sorry for the delay.

Yes, compilation was successful.

```
 ls -la ~/.local/share/xbase
total 18624
drwxr-xr-x  4 andre  staff      128 Sep 18 12:51 .
drwx------  7 andre  staff      224 Sep 18 12:51 ..
-rwxr-xr-x  1 andre  staff  5975587 Sep 18 12:51 xbase
-rwxr-xr-x  1 andre  staff  3557204 Sep 18 12:51 xbase-sourcekit-helper
```

And no, I'm not using a generator. I'm opening vim with no arguments in the folder which the `.xcodeproj` folder is located.

Ideally, I'd like to use `.xcworkspace` as a root and would be able to navigate all files inside any projects inside that workspace, but I'm not sure if this already supported.

To be clear though, I'm testing it against a single project (no `.xcworkspace` even present in the folder).

Cheers!

**Comment by kkharji** [comment]
hmm this is odd. Maybe something is broken with auto launcher.

`lua require'xbase.server'.register(vim.loop.cwd())`, I suggest first trying to run the server binary manually in a different terminal  `~/.local/share/xbase/xbase`

Could share with me how you've setup xbase, my an issue there or does it look similar to 

```lua
use {
  "xbase-lab/xbase",
  config = function ()
    require'xbase'.setup({
      log_level = vim.log.levels.INFO,
      log_buffer = {
        focus  = false,
        default_direction = "horizontal",
      },
      sourcekit = {
        on_attach = require'user.lsp'.on_attach(),
        handlers = require'user.lsp'.handlers,
        capabilities = require'user.lsp'.capabilities
      },
      simctl = {
        iOS = {
          "iPhone 13 Pro",
        },
      },
      mappings = {
        --- Whether xbase mapping should be disabled.
        enable = true,
        --- Open build picker. showing targets and configuration.
        build_picker = 0, --- set to 0 to disable
        --- Open run picker. showing targets, devices and configuration
        run_picker = 0, --- set to 0 to disable
        --- Open watch picker. showing run or build, targets, devices and configuration
        watch_picker = 0, --- set to 0 to disable
        --- A list of all the previous pickers
        all_picker = "<leader>ef", --- set to 0 to disable
      },
    })
  end
}
```

Yes, xcworkspace is supported to some extent.

Sorry for late response, I lost a family member to a heart condition this week.
